### ISSUE TITLE
Clearer saved command message

### ISSUE THREAD

**Issue by alcen** [AY1920S2-CS2103T-F09-1/main#149]
Take the date into account as well, e.g.

In total, you have saved RM17.50 as well as earned 1x Brattby Bag.
You saved RM17.50 as well as earned 1x Brattby Bag on 25 March 2020.
You saved RM17.50 as well as earned 1x Brattby Bag between 23 March 2020 and 25 March 2020.

instead of just

You have saved RM17.50 as well as earned 1x Brattby Bag.

**Comment by ChesterSim** [comment]
@alcen whats the progress for this?
