### ISSUE TITLE
Unnecessary Filter

### ISSUE THREAD

**Issue by ChesterSim** [AY1920S2-CS2103T-F09-1/main#347]
![Screenshot 2020-04-09 at 9 26 04 PM](https://user-images.githubusercontent.com/12388321/78899989-c49ded00-7aa8-11ea-9d81-8926ebe7fe33.png)

Don't need to filter by Model.PREDICATE_SHOW_ALL_COUPONS first

**Comment by Denise-Ng** [comment]
So when the user filters by something (i.e name), then it can be further filtered by expiring date?
